### ISSUE TITLE
couchdb views are not copied during install

### ISSUE THREAD

**Issue by serein7** [OpenAgInitiative/openag-brain#1]
I've noticed that after:
`pip3 install .`
no **js** files from _openag/brain/core/_design/_  subdirectories are copied and as a result db_init is failing to create corresponding couchdb views.
to fix this I had to create MANIFEST.in file in the project root directory (where setup.py is located)
`global-include *.js`
and modify setup.py with an extra parameter during setup function call:
`include_package_data=True`

**Comment by LeonChambers** [comment]
Cool, I suspected that this might happen but hadn't tested it yet. Could you submit a pull request with the fix?

**Comment by serein7** [comment]
Sure. Here it is https://github.com/OpenAgInitiative/openag-brain/pull/2
